[window]
opacity = 0.89
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true
padding = { x = 10, y = 10 }


[cursor]
style = "Underline"
unfocused_hollow = true


[env]
WINIT_UNIX_BACKEND = "wayland"

[font]
size = 12.0


[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[colors.primary]
background = "#000000"
foreground = "#E6E6E6"

[colors.cursor]
text = "#1E1E1E"
cursor = "#64B4FF"

[colors.selection]
text = "#FFFFFF"
background = "#3264C8"

[colors.normal]
black   = "#1E1E1E"
red     = "#B43232"
green   = "#5FAF5F"
yellow  = "#D7AF5F"
blue    = "#3264C8"
magenta = "#AF5FD7"
cyan    = "#64B4FF"
white   = "#E6E6E6"

[colors.bright]
black   = "#3A3A3A"
red     = "#FF5F5F"
green   = "#87D787"
yellow  = "#FFD787"
blue    = "#5F87FF"
magenta = "#D787FF"
cyan    = "#87D7FF"
white   = "#FFFFFF"
